packages:
  - apps/*
  - packages/*

catalogs:
  utils:
    "es-toolkit": "^1.38.0"
  mui7:
    "@mui/icons-material": "^7.1.0"
    "@mui/material": "^7.1.0"
    "@mui/material-nextjs": "^7.1.0"
    "@mui/x-date-pickers": "^8.5.0"
