packages:
  - apps/*
  - packages/*

catalogs:
  utils:
    "es-toolkit": "^1.37.2"
  mui7:
    "@mui/icons-material": "^7.0.2"
    "@mui/material": "^7.0.2"
    "@mui/material-nextjs": "^7.0.2"
    "@mui/x-date-pickers": "^8.0.0"
