packages:
  - apps/*
  - packages/*

catalogs:
  mui7:
    "@mui/icons-material": "^7.1.0"
    "@mui/material": "^7.1.0"
    "@mui/material-nextjs": "^7.1.0"
    "@mui/x-date-pickers": "^8.5.0"
  tests:
    "@vitest/browser": "^3.2.0"
    "@vitest/coverage-v8": "^3.2.0"
    "vitest": "^3.2.0"
  utils:
    "es-toolkit": "^1.38.0"
