// This file is automatically generated. Do not modify directly.
// Generated at: 2025-05-02T12:25:09.786Z

const TOKENS = {
  primitive: {
    color: {
      light: {
        primary: {
          "5": {
            value: "#ecf2fe",
            type: "color",
          },
          "10": {
            value: "#d8e5fd",
            type: "color",
          },
          "20": {
            value: "#b1cefb",
            type: "color",
          },
          "30": {
            value: "#86aff9",
            type: "color",
          },
          "40": {
            value: "#4c87f6",
            type: "color",
          },
          "50": {
            value: "#256ef4",
            type: "color",
          },
          "60": {
            value: "#0b50d0",
            type: "color",
          },
          "70": {
            value: "#083891",
            type: "color",
          },
          "80": {
            value: "#052561",
            type: "color",
          },
          "90": {
            value: "#03163a",
            type: "color",
          },
          "95": {
            value: "#020f27",
            type: "color",
          },
        },
        secondary: {
          "5": {
            value: "#eef2f7",
            type: "color",
          },
          "10": {
            value: "#d6e0eb",
            type: "color",
          },
          "20": {
            value: "#bacbde",
            type: "color",
          },
          "30": {
            value: "#90b0d5",
            type: "color",
          },
          "40": {
            value: "#6b96c7",
            type: "color",
          },
          "50": {
            value: "#346fb2",
            type: "color",
          },
          "60": {
            value: "#1c589c",
            type: "color",
          },
          "70": {
            value: "#063a74",
            type: "color",
          },
          "80": {
            value: "#052b57",
            type: "color",
          },
          "90": {
            value: "#031f3f",
            type: "color",
          },
          "95": {
            value: "#02162c",
            type: "color",
          },
        },
        gray: {
          "0": {
            value: "#ffffff",
            type: "color",
          },
          "5": {
            value: "#f4f5f6",
            type: "color",
          },
          "10": {
            value: "#e6e8ea",
            type: "color",
          },
          "20": {
            value: "#cdd1d5",
            type: "color",
          },
          "30": {
            value: "#b1b8be",
            type: "color",
          },
          "40": {
            value: "#8a949e",
            type: "color",
          },
          "50": {
            value: "#6d7882",
            type: "color",
          },
          "60": {
            value: "#58616a",
            type: "color",
          },
          "70": {
            value: "#464c53",
            type: "color",
          },
          "80": {
            value: "#33363d",
            type: "color",
          },
          "90": {
            value: "#1e2124",
            type: "color",
          },
          "95": {
            value: "#131416",
            type: "color",
          },
          "100": {
            value: "#000000",
            type: "color",
          },
        },
        alpha: {
          black100: {
            value: "#000000",
            type: "color",
            description: "text-title",
          },
          black75: {
            value: "#000000bf",
            type: "color",
            description: "dimmed",
          },
          black50: {
            value: "#00000080",
            type: "color",
            description: "bg,border",
          },
          black25: {
            value: "#00000040",
            type: "color",
            description: "bg,border",
          },
          black10: {
            value: "#0000001a",
            type: "color",
            description: "bg,border",
          },
          black0: {
            value: "#00000000",
            type: "color",
          },
          white100: {
            value: "#ffffff",
            type: "color",
            description: "text-title",
          },
          white75: {
            value: "#ffffffbf",
            type: "color",
            description: "dimmed",
          },
          white50: {
            value: "#ffffff80",
            type: "color",
            description: "bg,border",
          },
          white25: {
            value: "#ffffff40",
            type: "color",
            description: "bg,border",
          },
          white10: {
            value: "#ffffff1a",
            type: "color",
            description: "bg,border",
          },
          white0: {
            value: "#ffffff00",
            type: "color",
          },
        },
        danger: {
          "5": {
            value: "#fdefec",
            type: "color",
            description: "surface",
          },
          "10": {
            value: "#fcdfd9",
            type: "color",
            description: "border",
          },
          "20": {
            value: "#f7afa1",
            type: "color",
          },
          "30": {
            value: "#f48771",
            type: "color",
          },
          "40": {
            value: "#f05f42",
            type: "color",
          },
          "50": {
            value: "#de3412",
            type: "color",
            description: "base",
          },
          "60": {
            value: "#bd2c0f",
            type: "color",
            description: "text",
          },
          "70": {
            value: "#8a240f",
            type: "color",
          },
          "80": {
            value: "#5c180a",
            type: "color",
          },
          "90": {
            value: "#390d05",
            type: "color",
          },
          "95": {
            value: "#260903",
            type: "color",
          },
        },
        information: {
          "5": {
            value: "#e7f4fe",
            type: "color",
            description: "surface",
          },
          "10": {
            value: "#d3ebfd",
            type: "color",
            description: "border",
          },
          "20": {
            value: "#9ed2fa",
            type: "color",
          },
          "30": {
            value: "#5fb5f7",
            type: "color",
          },
          "40": {
            value: "#2098f3",
            type: "color",
          },
          "50": {
            value: "#0b78cb",
            type: "color",
            description: "base",
          },
          "60": {
            value: "#096ab3",
            type: "color",
            description: "text",
          },
          "70": {
            value: "#085691",
            type: "color",
          },
          "80": {
            value: "#053961",
            type: "color",
          },
          "90": {
            value: "#03253f",
            type: "color",
          },
          "95": {
            value: "#021a2c",
            type: "color",
          },
        },
        warning: {
          "5": {
            value: "#fff3db",
            type: "color",
            description: "surface",
          },
          "10": {
            value: "#ffe0a3",
            type: "color",
            description: "border",
          },
          "20": {
            value: "#ffc95c",
            type: "color",
          },
          "30": {
            value: "#ffb114",
            type: "color",
          },
          "40": {
            value: "#c78500",
            type: "color",
          },
          "50": {
            value: "#9e6a00",
            type: "color",
            description: "base",
          },
          "60": {
            value: "#8a5c00",
            type: "color",
            description: "text",
          },
          "70": {
            value: "#614100",
            type: "color",
          },
          "80": {
            value: "#422c00",
            type: "color",
          },
          "90": {
            value: "#2e1f00",
            type: "color",
          },
          "95": {
            value: "#241800",
            type: "color",
          },
        },
        success: {
          "5": {
            value: "#eaf6ec",
            type: "color",
            description: "surface",
          },
          "10": {
            value: "#d8eedd",
            type: "color",
            description: "border",
          },
          "20": {
            value: "#a9dab4",
            type: "color",
          },
          "30": {
            value: "#7ec88e",
            type: "color",
          },
          "40": {
            value: "#3fa654",
            type: "color",
          },
          "50": {
            value: "#228738",
            type: "color",
            description: "base",
          },
          "60": {
            value: "#267337",
            type: "color",
            description: "text",
          },
          "70": {
            value: "#285d33",
            type: "color",
          },
          "80": {
            value: "#1f4727",
            type: "color",
          },
          "90": {
            value: "#122b18",
            type: "color",
          },
          "95": {
            value: "#0e2012",
            type: "color",
          },
        },
        point: {
          "5": {
            value: "#fbeff0",
            type: "color",
          },
          "10": {
            value: "#f5d6d9",
            type: "color",
          },
          "20": {
            value: "#ebadb2",
            type: "color",
          },
          "30": {
            value: "#e0858c",
            type: "color",
          },
          "40": {
            value: "#d65c66",
            type: "color",
          },
          "50": {
            value: "#d63d4a",
            type: "color",
          },
          "60": {
            value: "#ab2b36",
            type: "color",
          },
          "70": {
            value: "#7a1f26",
            type: "color",
          },
          "80": {
            value: "#521419",
            type: "color",
          },
          "90": {
            value: "#310c0f",
            type: "color",
          },
          "95": {
            value: "#21080a",
            type: "color",
          },
        },
        graphic: {
          "10": {
            value: "#e5ecf9",
            type: "color",
          },
          "30": {
            value: "#98acc5",
            type: "color",
          },
          "50": {
            value: "#61758f",
            type: "color",
          },
          "70": {
            value: "#39506c",
            type: "color",
          },
          "90": {
            value: "#223a58",
            type: "color",
          },
        },
      },
      "high-contrast": {
        gray: {
          "0": {
            value: "#ffffff",
            type: "color",
          },
          "5": {
            value: "#f4f5f6",
            type: "color",
          },
          "10": {
            value: "#e6e8ea",
            type: "color",
          },
          "20": {
            value: "#cdd1d5",
            type: "color",
          },
          "30": {
            value: "#b1b8be",
            type: "color",
          },
          "40": {
            value: "#8a949e",
            type: "color",
          },
          "50": {
            value: "#6d7882",
            type: "color",
          },
          "60": {
            value: "#58616a",
            type: "color",
          },
          "70": {
            value: "#464c53",
            type: "color",
          },
          "80": {
            value: "#33363d",
            type: "color",
          },
          "90": {
            value: "#1e2124",
            type: "color",
          },
          "95": {
            value: "#131416",
            type: "color",
          },
          "100": {
            value: "#000000",
            type: "color",
          },
        },
        primary: {
          "5": {
            value: "#ecf2fe",
            type: "color",
          },
          "10": {
            value: "#d8e5fd",
            type: "color",
          },
          "20": {
            value: "#b1cefb",
            type: "color",
          },
          "30": {
            value: "#86aff9",
            type: "color",
          },
          "40": {
            value: "#4c87f6",
            type: "color",
          },
          "50": {
            value: "#256ef4",
            type: "color",
          },
          "60": {
            value: "#0b50d0",
            type: "color",
          },
          "70": {
            value: "#083891",
            type: "color",
          },
          "80": {
            value: "#052561",
            type: "color",
          },
          "90": {
            value: "#03163a",
            type: "color",
          },
          "95": {
            value: "#020f27",
            type: "color",
          },
        },
        secondary: {
          "5": {
            value: "#edf6f8",
            type: "color",
          },
          "10": {
            value: "#d5ebf1",
            type: "color",
          },
          "20": {
            value: "#abd8e3",
            type: "color",
          },
          "30": {
            value: "#75c0d1",
            type: "color",
          },
          "40": {
            value: "#3d9fb8",
            type: "color",
          },
          "50": {
            value: "#268097",
            type: "color",
          },
          "60": {
            value: "#1f687a",
            type: "color",
          },
          "70": {
            value: "#17505e",
            type: "color",
          },
          "80": {
            value: "#113b45",
            type: "color",
          },
          "90": {
            value: "#0e3139",
            type: "color",
          },
          "95": {
            value: "#091f25",
            type: "color",
          },
        },
        point: {
          "5": {
            value: "#fbeff0",
            type: "color",
          },
          "10": {
            value: "#f5d6d9",
            type: "color",
          },
          "20": {
            value: "#ebadb2",
            type: "color",
          },
          "30": {
            value: "#e0858c",
            type: "color",
          },
          "40": {
            value: "#d65c66",
            type: "color",
          },
          "50": {
            value: "#d63d4a",
            type: "color",
          },
          "60": {
            value: "#ab2b36",
            type: "color",
          },
          "70": {
            value: "#7a1f26",
            type: "color",
          },
          "80": {
            value: "#521419",
            type: "color",
          },
          "90": {
            value: "#310c0f",
            type: "color",
          },
          "95": {
            value: "#21080a",
            type: "color",
          },
        },
        danger: {
          "5": {
            value: "#fdefec",
            type: "color",
            description: "surface",
          },
          "10": {
            value: "#fcdfd9",
            type: "color",
            description: "border",
          },
          "20": {
            value: "#f7afa1",
            type: "color",
          },
          "30": {
            value: "#f48771",
            type: "color",
          },
          "40": {
            value: "#f05f42",
            type: "color",
          },
          "50": {
            value: "#de3412",
            type: "color",
            description: "base",
          },
          "60": {
            value: "#bd2c0f",
            type: "color",
            description: "text",
          },
          "70": {
            value: "#8a240f",
            type: "color",
          },
          "80": {
            value: "#5c180a",
            type: "color",
          },
          "90": {
            value: "#390d05",
            type: "color",
          },
          "95": {
            value: "#260903",
            type: "color",
          },
        },
        warning: {
          "5": {
            value: "#fff3db",
            type: "color",
            description: "surface",
          },
          "10": {
            value: "#ffe0a3",
            type: "color",
            description: "border",
          },
          "20": {
            value: "#ffc95c",
            type: "color",
          },
          "30": {
            value: "#ffb114",
            type: "color",
          },
          "40": {
            value: "#c78500",
            type: "color",
          },
          "50": {
            value: "#9e6a00",
            type: "color",
            description: "base",
          },
          "60": {
            value: "#8a5c00",
            type: "color",
            description: "text",
          },
          "70": {
            value: "#614100",
            type: "color",
          },
          "80": {
            value: "#422c00",
            type: "color",
          },
          "90": {
            value: "#2e1f00",
            type: "color",
          },
          "95": {
            value: "#241800",
            type: "color",
          },
        },
        success: {
          "5": {
            value: "#eaf6ec",
            type: "color",
            description: "surface",
          },
          "10": {
            value: "#d8eedd",
            type: "color",
            description: "border",
          },
          "20": {
            value: "#a9dab4",
            type: "color",
          },
          "30": {
            value: "#7ec88e",
            type: "color",
          },
          "40": {
            value: "#3fa654",
            type: "color",
          },
          "50": {
            value: "#228738",
            type: "color",
            description: "base",
          },
          "60": {
            value: "#267337",
            type: "color",
            description: "text",
          },
          "70": {
            value: "#285d33",
            type: "color",
          },
          "80": {
            value: "#1f4727",
            type: "color",
          },
          "90": {
            value: "#122b18",
            type: "color",
          },
          "95": {
            value: "#0e2012",
            type: "color",
          },
        },
        information: {
          "5": {
            value: "#e7f4fe",
            type: "color",
            description: "surface",
          },
          "10": {
            value: "#d3ebfd",
            type: "color",
            description: "border",
          },
          "20": {
            value: "#9ed2fa",
            type: "color",
          },
          "30": {
            value: "#5fb5f7",
            type: "color",
          },
          "40": {
            value: "#2098f3",
            type: "color",
          },
          "50": {
            value: "#0b78cb",
            type: "color",
            description: "base",
          },
          "60": {
            value: "#096ab3",
            type: "color",
            description: "text",
          },
          "70": {
            value: "#085691",
            type: "color",
          },
          "80": {
            value: "#053961",
            type: "color",
          },
          "90": {
            value: "#03253f",
            type: "color",
          },
          "95": {
            value: "#021a2c",
            type: "color",
          },
        },
        alpha: {
          black100: {
            value: "#000000",
            type: "color",
            description: "text-title",
          },
          black75: {
            value: "#000000bf",
            type: "color",
            description: "dimmed",
          },
          black50: {
            value: "#00000080",
            type: "color",
            description: "bg,border",
          },
          black25: {
            value: "#00000040",
            type: "color",
            description: "bg,border",
          },
          black10: {
            value: "#0000001a",
            type: "color",
            description: "bg,border",
          },
          black0: {
            value: "#00000000",
            type: "color",
          },
          white100: {
            value: "#ffffff",
            type: "color",
            description: "text-title",
          },
          white75: {
            value: "#ffffffbf",
            type: "color",
            description: "dimmed",
          },
          white50: {
            value: "#ffffff80",
            type: "color",
            description: "bg,border",
          },
          white25: {
            value: "#ffffff40",
            type: "color",
            description: "bg,border",
          },
          white10: {
            value: "#ffffff1a",
            type: "color",
            description: "bg,border",
          },
          white0: {
            value: "#ffffff00",
            type: "color",
          },
        },
        graphic: {
          "10": {
            value: "#e5ecf9",
            type: "color",
          },
          "30": {
            value: "#98acc5",
            type: "color",
          },
          "50": {
            value: "#61758f",
            type: "color",
          },
          "70": {
            value: "#39506c",
            type: "color",
          },
          "90": {
            value: "#223a58",
            type: "color",
          },
        },
      },
    },
    typo: {
      font: {
        type: {
          value: "Pretendard GOV",
          type: "text",
        },
      },
      "font-weight": {
        regular: {
          value: "Regular",
          type: "text",
        },
        bold: {
          value: "Bold",
          type: "text",
        },
      },
      "letter-spacing": {
        "0": {
          value: "0rem",
          type: "dimension",
        },
        "1": {
          value: "0.1rem",
          type: "dimension",
        },
      },
    },
    number: {
      "0": {
        value: "0rem",
        type: "dimension",
      },
      "1": {
        value: "0.1rem",
        type: "dimension",
      },
      "2": {
        value: "0.2rem",
        type: "dimension",
      },
      "3": {
        value: "0.4rem",
        type: "dimension",
      },
      "4": {
        value: "0.6rem",
        type: "dimension",
      },
      "5": {
        value: "0.8rem",
        type: "dimension",
      },
      "6": {
        value: "1rem",
        type: "dimension",
      },
      "7": {
        value: "1.2rem",
        type: "dimension",
      },
      "8": {
        value: "1.6rem",
        type: "dimension",
      },
      "9": {
        value: "2rem",
        type: "dimension",
      },
      "10": {
        value: "2.4rem",
        type: "dimension",
      },
      "11": {
        value: "2.8rem",
        type: "dimension",
      },
      "12": {
        value: "3.2rem",
        type: "dimension",
      },
      "13": {
        value: "3.6rem",
        type: "dimension",
      },
      "14": {
        value: "4rem",
        type: "dimension",
      },
      "15": {
        value: "4.4rem",
        type: "dimension",
      },
      "16": {
        value: "4.8rem",
        type: "dimension",
      },
      "17": {
        value: "5.6rem",
        type: "dimension",
      },
      "18": {
        value: "6.4rem",
        type: "dimension",
      },
      "19": {
        value: "7.2rem",
        type: "dimension",
      },
      "20": {
        value: "8rem",
        type: "dimension",
      },
      "21": {
        value: "9.6rem",
        type: "dimension",
      },
      max: {
        value: "100rem",
        type: "dimension",
      },
    },
  },
  "mode-light": {
    color: {
      surface: {
        "gray-subtler": {
          value: "#f4f5f6",
          type: "color",
        },
        "gray-subtle": {
          value: "#e6e8ea",
          type: "color",
        },
        disabled: {
          value: "#cdd1d5",
          type: "color",
          description: "disabled",
        },
        "primary-subtler": {
          value: "#ecf2fe",
          type: "color",
        },
        "secondary-subtler": {
          value: "#eef2f7",
          type: "color",
        },
        "danger-subtler": {
          value: "#fdefec",
          type: "color",
        },
        "warning-subtler": {
          value: "#fff3db",
          type: "color",
        },
        "success-subtler": {
          value: "#eaf6ec",
          type: "color",
        },
        "information-subtler": {
          value: "#e7f4fe",
          type: "color",
        },
        "point-subtler": {
          value: "#fbeff0",
          type: "color",
        },
        white: {
          value: "#ffffff",
          type: "color",
          description: "disabled",
        },
        inverse: {
          value: "#1e2124",
          type: "color",
          description: "disabled",
        },
        "white-static": {
          value: "#ffffff",
          type: "color",
          description: "disabled",
        },
        "inverse-static": {
          value: "#1e2124",
          type: "color",
          description: "disabled",
        },
        "white-subtle": {
          value: "#ffffff",
          type: "color",
          description: "disabled",
        },
        "white-subtler": {
          value: "#ffffff",
          type: "color",
          description: "disabled",
        },
      },
      border: {
        "gray-light": {
          value: "#cdd1d5",
          type: "color",
        },
        gray: {
          value: "#b1b8be",
          type: "color",
          description: "disabled",
        },
        "secondary-light": {
          value: "#d6e0eb",
          type: "color",
        },
        "danger-light": {
          value: "#fcdfd9",
          type: "color",
        },
        danger: {
          value: "#de3412",
          type: "color",
        },
        "warning-light": {
          value: "#ffe0a3",
          type: "color",
        },
        warning: {
          value: "#9e6a00",
          type: "color",
        },
        "success-light": {
          value: "#d8eedd",
          type: "color",
        },
        success: {
          value: "#228738",
          type: "color",
        },
        "information-light": {
          value: "#d3ebfd",
          type: "color",
        },
        information: {
          value: "#0b78cb",
          type: "color",
        },
        "gray-dark": {
          value: "#58616a",
          type: "color",
          description: "active",
        },
        primary: {
          value: "#256ef4",
          type: "color",
          description: "active/selected",
        },
        disabled: {
          value: "#b1b8be",
          type: "color",
          description: "disabled",
        },
        "gray-darker": {
          value: "#1e2124",
          type: "color",
          description: "active",
        },
        secondary: {
          value: "#063a74",
          type: "color",
          description: "active/selected",
        },
        inverse: {
          value: "#ffffff",
          type: "color",
          description: "disabled",
        },
        transparency: {
          value: "#00000000",
          type: "color",
          description: "disabled",
        },
        "primary-light": {
          value: "#d8e5fd",
          type: "color",
          description: "active/selected",
        },
        point: {
          value: "#d63d4a",
          type: "color",
          description: "active/selected",
        },
        "point-light": {
          value: "#f5d6d9",
          type: "color",
          description: "active/selected",
        },
      },
      divider: {
        "gray-light": {
          value: "#cdd1d5",
          type: "color",
        },
        gray: {
          value: "#8a949e",
          type: "color",
          description: "disabled",
        },
        "gray-dark": {
          value: "#6d7882",
          type: "color",
          description: "active",
        },
        primary: {
          value: "#256ef4",
          type: "color",
          description: "active/selected",
        },
        "secondary-light": {
          value: "#d6e0eb",
          type: "color",
        },
        secondary: {
          value: "#063a74",
          type: "color",
          description: "active/selected",
        },
        error: {
          value: "#de3412",
          type: "color",
        },
        "primary-light": {
          value: "#d8e5fd",
          type: "color",
          description: "active/selected",
        },
        inverse: {
          value: "#ffffff",
          type: "color",
        },
        "gray-darker": {
          value: "#1e2124",
          type: "color",
          description: "active",
        },
        point: {
          value: "#d63d4a",
          type: "color",
        },
      },
      text: {
        bolder: {
          value: "#131416",
          type: "color",
        },
        subtle: {
          value: "#464c53",
          type: "color",
        },
        disabled: {
          value: "#8a949e",
          type: "color",
          description: "disabled",
        },
        "disabled-on": {
          value: "#6d7882",
          type: "color",
          description: "active",
        },
        primary: {
          value: "#0b50d0",
          type: "color",
          description: "active/selected",
        },
        secondary: {
          value: "#052b57",
          type: "color",
          description: "active/selected",
        },
        danger: {
          value: "#bd2c0f",
          type: "color",
        },
        warning: {
          value: "#8a5c00",
          type: "color",
        },
        success: {
          value: "#267337",
          type: "color",
        },
        information: {
          value: "#096ab3",
          type: "color",
        },
        basic: {
          value: "#1e2124",
          type: "color",
        },
        point: {
          value: "#ab2b36",
          type: "color",
        },
        "bolder-inverse": {
          value: "#ffffff",
          type: "color",
        },
        "basic-inverse": {
          value: "#ffffff",
          type: "color",
        },
        "subtle-inverse": {
          value: "#b1b8be",
          type: "color",
        },
        "inverse-static": {
          value: "#ffffff",
          type: "color",
        },
        static: {
          value: "#1e2124",
          type: "color",
        },
      },
      icon: {
        gray: {
          value: "#33363d",
          type: "color",
        },
        "gray-fill": {
          value: "#cdd1d5",
          type: "color",
        },
        inverse: {
          value: "#ffffff",
          type: "color",
        },
        primary: {
          value: "#256ef4",
          type: "color",
          description: "active/selected",
        },
        secondary: {
          value: "#052b57",
          type: "color",
          description: "active/selected",
        },
        point: {
          value: "#d63d4a",
          type: "color",
        },
        danger: {
          value: "#de3412",
          type: "color",
        },
        warning: {
          value: "#9e6a00",
          type: "color",
        },
        success: {
          value: "#228738",
          type: "color",
        },
        information: {
          value: "#0b78cb",
          type: "color",
        },
        "gray-light": {
          value: "#464c53",
          type: "color",
        },
        disabled: {
          value: "#8a949e",
          type: "color",
        },
        "disabled-on": {
          value: "#6d7882",
          type: "color",
        },
        "inverse-static": {
          value: "#ffffff",
          type: "color",
        },
        "primary-static": {
          value: "#256ef4",
          type: "color",
          description: "active/selected",
        },
        "secondary-static": {
          value: "#052b57",
          type: "color",
          description: "active/selected",
        },
        "point-static": {
          value: "#d63d4a",
          type: "color",
        },
        "danger-static": {
          value: "#de3412",
          type: "color",
        },
        "warning-static": {
          value: "#9e6a00",
          type: "color",
        },
        "success-static": {
          value: "#228738",
          type: "color",
        },
        "information-static": {
          value: "#0b78cb",
          type: "color",
        },
        "gray-static": {
          value: "#33363d",
          type: "color",
        },
      },
      link: {
        default: {
          value: "#256ef4",
          type: "color",
        },
        hover: {
          value: "#0b50d0",
          type: "color",
        },
        pressed: {
          value: "#083891",
          type: "color",
        },
        visited: {
          value: "#5917b8",
          type: "color",
        },
      },
      button: {
        "primary-fill": {
          value: "#256ef4",
          type: "color",
        },
        "primary-fill-hover": {
          value: "#0b50d0",
          type: "color",
        },
        "primary-fill-pressed": {
          value: "#083891",
          type: "color",
        },
        "secondary-fill": {
          value: "#ecf2fe",
          type: "color",
        },
        "secondary-fill-hover": {
          value: "#d8e5fd",
          type: "color",
        },
        "secondary-fill-pressed": {
          value: "#b1cefb",
          type: "color",
        },
        "secondary-border": {
          value: "#256ef4",
          type: "color",
        },
        "tertiary-fill": {
          value: "#ffffff00",
          type: "color",
        },
        "tertiary-fill-hover": {
          value: "#f4f5f6",
          type: "color",
        },
        "tertiary-fill-pressed": {
          value: "#e6e8ea",
          type: "color",
        },
        "tertiary-border": {
          value: "#58616a",
          type: "color",
        },
        "disabled-fill": {
          value: "#cdd1d5",
          type: "color",
        },
        "text-fill-hover": {
          value: "#eef2f7",
          type: "color",
        },
        "text-fill-pressed": {
          value: "#d6e0eb",
          type: "color",
        },
        "text-fill": {
          value: "#ffffff00",
          type: "color",
        },
        "text-border": {
          value: "#00000000",
          type: "color",
        },
        "disabled-border": {
          value: "#b1b8be",
          type: "color",
        },
      },
      background: {
        white: {
          value: "#ffffff",
          type: "color",
        },
        inverse: {
          value: "#1e2124",
          type: "color",
        },
        "gray-subtler": {
          value: "#f4f5f6",
          type: "color",
        },
        "gray-subtle": {
          value: "#e6e8ea",
          type: "color",
        },
        dim: {
          value: "#000000bf",
          type: "color",
        },
      },
      element: {
        "disabled-light": {
          value: "#cdd1d5",
          type: "color",
          description: "앞에 gray를 붙",
        },
        "disabled-dark": {
          value: "#8a949e",
          type: "color",
          description: "disabled",
        },
        "gray-lighter": {
          value: "#f4f5f6",
          type: "color",
        },
        "gray-light": {
          value: "#e6e8ea",
          type: "color",
        },
        gray: {
          value: "#6d7882",
          type: "color",
        },
        "primary-lighter": {
          value: "#ecf2fe",
          type: "color",
        },
        "primary-light": {
          value: "#d8e5fd",
          type: "color",
        },
        primary: {
          value: "#256ef4",
          type: "color",
          description: "active/selected",
        },
        "secondary-lighter": {
          value: "#eef2f7",
          type: "color",
        },
        "secondary-light": {
          value: "#d6e0eb",
          type: "color",
        },
        secondary: {
          value: "#063a74",
          type: "color",
        },
        "point-lighter": {
          value: "#fbeff0",
          type: "color",
        },
        "point-light": {
          value: "#f5d6d9",
          type: "color",
        },
        point: {
          value: "#d63d4a",
          type: "color",
        },
        "danger-lighter": {
          value: "#fdefec",
          type: "color",
        },
        danger: {
          value: "#de3412",
          type: "color",
        },
        "warning-lighter": {
          value: "#fff3db",
          type: "color",
        },
        warning: {
          value: "#ffb114",
          type: "color",
        },
        "success-lighter": {
          value: "#eaf6ec",
          type: "color",
        },
        success: {
          value: "#228738",
          type: "color",
        },
        "information-lighter": {
          value: "#e7f4fe",
          type: "color",
        },
        information: {
          value: "#0b78cb",
          type: "color",
        },
        inverse: {
          value: "#ffffff",
          type: "color",
        },
        "gray-dark": {
          value: "#58616a",
          type: "color",
        },
        "inverse-static": {
          value: "#ffffff",
          type: "color",
        },
      },
      action: {
        white: {
          value: "#ffffff",
          type: "color",
          description: "disabled",
        },
        primary: {
          value: "#ffffff00",
          type: "color",
        },
        "primary-hover": {
          value: "#ecf2fe",
          type: "color",
        },
        "primary-pressed": {
          value: "#d8e5fd",
          type: "color",
        },
        secondary: {
          value: "#ffffff00",
          type: "color",
        },
        "secondary-hover": {
          value: "#eef2f7",
          type: "color",
        },
        "secondary-pressed": {
          value: "#d6e0eb",
          type: "color",
        },
        "secondary-selected": {
          value: "#eef2f7",
          type: "color",
        },
        "secondary-on": {
          value: "#ffffff00",
          type: "color",
        },
        "secondary-on-hover": {
          value: "#ffffff",
          type: "color",
        },
        "secondary-on-pressed": {
          value: "#d6e0eb",
          type: "color",
        },
        "secondary-on-selected": {
          value: "#ffffff",
          type: "color",
        },
        "secondary-active": {
          value: "#063a74",
          type: "color",
        },
        "primary-active": {
          value: "#256ef4",
          type: "color",
        },
        disabled: {
          value: "#cdd1d5",
          type: "color",
        },
        "primary-selected": {
          value: "#ecf2fe",
          type: "color",
        },
      },
      input: {
        border: {
          value: "#58616a",
          type: "color",
        },
        "border-disabled": {
          value: "#b1b8be",
          type: "color",
        },
        "border-active": {
          value: "#256ef4",
          type: "color",
          description: "active/selected",
        },
        "border-error": {
          value: "#de3412",
          type: "color",
        },
        surface: {
          value: "#ffffff",
          type: "color",
        },
        "surface-disabled": {
          value: "#cdd1d5",
          type: "color",
        },
      },
      graphic: {
        "blue-subtler": {
          value: "#e5ecf9",
          type: "color",
          description: "disabled",
        },
        "blue-subtle": {
          value: "#98acc5",
          type: "color",
          description: "disabled",
        },
        blue: {
          value: "#61758f",
          type: "color",
          description: "disabled",
        },
        "blue-dark": {
          value: "#39506c",
          type: "color",
          description: "disabled",
        },
        "blue-darker": {
          value: "#223a58",
          type: "color",
          description: "disabled",
        },
        "red-subtler": {
          value: "#fbeff0",
          type: "color",
          description: "disabled",
        },
        "red-subtle": {
          value: "#f5d6d9",
          type: "color",
          description: "disabled",
        },
        red: {
          value: "#ebadb2",
          type: "color",
          description: "disabled",
        },
        "red-dark": {
          value: "#d65c66",
          type: "color",
          description: "disabled",
        },
        "red-darker": {
          value: "#7a1f26",
          type: "color",
          description: "disabled",
        },
        brand: {
          value: "#256ef4",
          type: "color",
          description: "disabled",
        },
      },
      alpha: {
        base100: {
          value: "#ffffff",
          type: "color",
        },
        base50: {
          value: "#ffffff80",
          type: "color",
        },
        base25: {
          value: "#ffffff40",
          type: "color",
        },
        base0: {
          value: "#ffffff00",
          type: "color",
        },
        inverse100: {
          value: "#000000",
          type: "color",
        },
        inverse50: {
          value: "#00000080",
          type: "color",
        },
        inverse25: {
          value: "#00000040",
          type: "color",
        },
        inverse0: {
          value: "#00000000",
          type: "color",
        },
        base75: {
          value: "#ffffffbf",
          type: "color",
        },
        inverse75: {
          value: "#000000bf",
          type: "color",
        },
        inverse10: {
          value: "#0000001a",
          type: "color",
        },
        base10: {
          value: "#ffffff1a",
          type: "color",
        },
        shadow1: {
          value: "#0000000d",
          type: "color",
        },
        shadow2: {
          value: "#00000014",
          type: "color",
        },
        shadow3: {
          value: "#0000001f",
          type: "color",
        },
      },
    },
    "border-width": {
      "variable-regular": {
        value: "0.1rem",
        type: "dimension",
      },
      "variable-medium": {
        value: "0.2rem",
        type: "dimension",
      },
      "static-regular": {
        value: "0.1rem",
        type: "dimension",
      },
      "static-medium": {
        value: "0.2rem",
        type: "dimension",
      },
    },
  },
  "mode-high-contrast": {
    color: {
      surface: {
        "gray-subtler": {
          value: "#131416",
          type: "color",
        },
        "gray-subtle": {
          value: "#1e2124",
          type: "color",
        },
        disabled: {
          value: "#464c53",
          type: "color",
          description: "disabled",
        },
        "primary-subtler": {
          value: "#020f27",
          type: "color",
        },
        "secondary-subtler": {
          value: "#091f25",
          type: "color",
        },
        "danger-subtler": {
          value: "#260903",
          type: "color",
        },
        "warning-subtler": {
          value: "#241800",
          type: "color",
        },
        "success-subtler": {
          value: "#0e2012",
          type: "color",
        },
        "information-subtler": {
          value: "#021a2c",
          type: "color",
        },
        "point-subtler": {
          value: "#21080a",
          type: "color",
        },
        white: {
          value: "#000000",
          type: "color",
          description: "disabled",
        },
        inverse: {
          value: "#e6e8ea",
          type: "color",
          description: "disabled",
        },
        "white-static": {
          value: "#ffffff",
          type: "color",
          description: "disabled",
        },
        "inverse-static": {
          value: "#1e2124",
          type: "color",
          description: "disabled",
        },
        "white-subtle": {
          value: "#131416",
          type: "color",
          description: "disabled",
        },
        "white-subtler": {
          value: "#1e2124",
          type: "color",
          description: "disabled",
        },
      },
      border: {
        "gray-light": {
          value: "#33363d",
          type: "color",
        },
        gray: {
          value: "#464c53",
          type: "color",
          description: "disabled",
        },
        "secondary-light": {
          value: "#0e3139",
          type: "color",
        },
        "danger-light": {
          value: "#390d05",
          type: "color",
        },
        danger: {
          value: "#de3412",
          type: "color",
        },
        "warning-light": {
          value: "#2e1f00",
          type: "color",
        },
        warning: {
          value: "#9e6a00",
          type: "color",
        },
        "success-light": {
          value: "#122b18",
          type: "color",
        },
        success: {
          value: "#228738",
          type: "color",
        },
        "information-light": {
          value: "#03253f",
          type: "color",
        },
        information: {
          value: "#0b78cb",
          type: "color",
        },
        "gray-dark": {
          value: "#8a949e",
          type: "color",
          description: "active",
        },
        primary: {
          value: "#256ef4",
          type: "color",
          description: "active/selected",
        },
        disabled: {
          value: "#464c53",
          type: "color",
          description: "disabled",
        },
        "gray-darker": {
          value: "#e6e8ea",
          type: "color",
          description: "active",
        },
        secondary: {
          value: "#1f687a",
          type: "color",
          description: "active/selected",
        },
        inverse: {
          value: "#000000",
          type: "color",
          description: "disabled",
        },
        transparency: {
          value: "#ffffff40",
          type: "color",
          description: "disabled",
        },
        "primary-light": {
          value: "#03163a",
          type: "color",
          description: "active/selected",
        },
        point: {
          value: "#d63d4a",
          type: "color",
          description: "active/selected",
        },
        "point-light": {
          value: "#310c0f",
          type: "color",
          description: "active/selected",
        },
      },
      divider: {
        "gray-light": {
          value: "#33363d",
          type: "color",
        },
        gray: {
          value: "#464c53",
          type: "color",
          description: "disabled",
        },
        "gray-dark": {
          value: "#6d7882",
          type: "color",
          description: "active",
        },
        primary: {
          value: "#256ef4",
          type: "color",
          description: "active/selected",
        },
        "secondary-light": {
          value: "#0e3139",
          type: "color",
        },
        secondary: {
          value: "#1f687a",
          type: "color",
          description: "active/selected",
        },
        error: {
          value: "#de3412",
          type: "color",
        },
        "primary-light": {
          value: "#03163a",
          type: "color",
          description: "active/selected",
        },
        inverse: {
          value: "#000000",
          type: "color",
        },
        "gray-darker": {
          value: "#e6e8ea",
          type: "color",
          description: "active",
        },
        point: {
          value: "#d63d4a",
          type: "color",
        },
      },
      text: {
        bolder: {
          value: "#e6e8ea",
          type: "color",
        },
        subtle: {
          value: "#cdd1d5",
          type: "color",
        },
        disabled: {
          value: "#58616a",
          type: "color",
          description: "disabled",
        },
        "disabled-on": {
          value: "#6d7882",
          type: "color",
          description: "active",
        },
        primary: {
          value: "#b1cefb",
          type: "color",
          description: "active/selected",
        },
        secondary: {
          value: "#abd8e3",
          type: "color",
          description: "active/selected",
        },
        danger: {
          value: "#f7afa1",
          type: "color",
        },
        warning: {
          value: "#ffc95c",
          type: "color",
        },
        success: {
          value: "#a9dab4",
          type: "color",
        },
        information: {
          value: "#9ed2fa",
          type: "color",
        },
        basic: {
          value: "#f4f5f6",
          type: "color",
        },
        point: {
          value: "#ebadb2",
          type: "color",
        },
        "bolder-inverse": {
          value: "#131416",
          type: "color",
        },
        "basic-inverse": {
          value: "#1e2124",
          type: "color",
        },
        "subtle-inverse": {
          value: "#464c53",
          type: "color",
        },
        "inverse-static": {
          value: "#ffffff",
          type: "color",
        },
        static: {
          value: "#1e2124",
          type: "color",
        },
      },
      icon: {
        gray: {
          value: "#f4f5f6",
          type: "color",
        },
        "gray-fill": {
          value: "#464c53",
          type: "color",
        },
        inverse: {
          value: "#1e2124",
          type: "color",
        },
        primary: {
          value: "#b1cefb",
          type: "color",
          description: "active/selected",
        },
        secondary: {
          value: "#abd8e3",
          type: "color",
          description: "active/selected",
        },
        point: {
          value: "#ebadb2",
          type: "color",
        },
        danger: {
          value: "#f7afa1",
          type: "color",
        },
        warning: {
          value: "#ffc95c",
          type: "color",
        },
        success: {
          value: "#a9dab4",
          type: "color",
        },
        information: {
          value: "#9ed2fa",
          type: "color",
        },
        "gray-light": {
          value: "#cdd1d5",
          type: "color",
        },
        disabled: {
          value: "#58616a",
          type: "color",
        },
        "disabled-on": {
          value: "#6d7882",
          type: "color",
        },
        "inverse-static": {
          value: "#ffffff",
          type: "color",
        },
        "primary-static": {
          value: "#256ef4",
          type: "color",
          description: "active/selected",
        },
        "secondary-static": {
          value: "#113b45",
          type: "color",
          description: "active/selected",
        },
        "point-static": {
          value: "#d63d4a",
          type: "color",
        },
        "danger-static": {
          value: "#de3412",
          type: "color",
        },
        "warning-static": {
          value: "#9e6a00",
          type: "color",
        },
        "success-static": {
          value: "#228738",
          type: "color",
        },
        "information-static": {
          value: "#0b78cb",
          type: "color",
        },
        "gray-static": {
          value: "#33363d",
          type: "color",
        },
      },
      link: {
        default: {
          value: "#86aff9",
          type: "color",
        },
        hover: {
          value: "#b1cefb",
          type: "color",
        },
        pressed: {
          value: "#d8e5fd",
          type: "color",
        },
        visited: {
          value: "#c49ff9",
          type: "color",
        },
      },
      button: {
        "primary-fill": {
          value: "#256ef4",
          type: "color",
        },
        "primary-fill-hover": {
          value: "#0b50d0",
          type: "color",
        },
        "primary-fill-pressed": {
          value: "#083891",
          type: "color",
        },
        "secondary-fill": {
          value: "#020f27",
          type: "color",
        },
        "secondary-fill-hover": {
          value: "#03163a",
          type: "color",
        },
        "secondary-fill-pressed": {
          value: "#052561",
          type: "color",
        },
        "secondary-border": {
          value: "#256ef4",
          type: "color",
        },
        "tertiary-fill": {
          value: "#00000000",
          type: "color",
        },
        "tertiary-fill-hover": {
          value: "#131416",
          type: "color",
        },
        "tertiary-fill-pressed": {
          value: "#33363d",
          type: "color",
        },
        "tertiary-border": {
          value: "#8a949e",
          type: "color",
        },
        "disabled-fill": {
          value: "#33363d",
          type: "color",
        },
        "text-fill-hover": {
          value: "#091f25",
          type: "color",
        },
        "text-fill-pressed": {
          value: "#0e3139",
          type: "color",
        },
        "text-fill": {
          value: "#00000000",
          type: "color",
        },
        "text-border": {
          value: "#ffffff80",
          type: "color",
        },
        "disabled-border": {
          value: "#464c53",
          type: "color",
        },
      },
      background: {
        white: {
          value: "#000000",
          type: "color",
        },
        inverse: {
          value: "#e6e8ea",
          type: "color",
        },
        "gray-subtler": {
          value: "#131416",
          type: "color",
        },
        "gray-subtle": {
          value: "#1e2124",
          type: "color",
        },
        dim: {
          value: "#000000bf",
          type: "color",
        },
      },
      element: {
        "disabled-light": {
          value: "#33363d",
          type: "color",
          description: "앞에 gray를 붙",
        },
        "disabled-dark": {
          value: "#58616a",
          type: "color",
          description: "disabled",
        },
        "gray-lighter": {
          value: "#131416",
          type: "color",
        },
        "gray-light": {
          value: "#1e2124",
          type: "color",
        },
        gray: {
          value: "#6d7882",
          type: "color",
        },
        "primary-lighter": {
          value: "#020f27",
          type: "color",
        },
        "primary-light": {
          value: "#03163a",
          type: "color",
        },
        primary: {
          value: "#256ef4",
          type: "color",
          description: "active/selected",
        },
        "secondary-lighter": {
          value: "#091f25",
          type: "color",
        },
        "secondary-light": {
          value: "#0e3139",
          type: "color",
        },
        secondary: {
          value: "#1f687a",
          type: "color",
        },
        "point-lighter": {
          value: "#21080a",
          type: "color",
        },
        "point-light": {
          value: "#310c0f",
          type: "color",
        },
        point: {
          value: "#d63d4a",
          type: "color",
        },
        "danger-lighter": {
          value: "#260903",
          type: "color",
        },
        danger: {
          value: "#de3412",
          type: "color",
        },
        "warning-lighter": {
          value: "#241800",
          type: "color",
        },
        warning: {
          value: "#ffb114",
          type: "color",
        },
        "success-lighter": {
          value: "#0e2012",
          type: "color",
        },
        success: {
          value: "#228738",
          type: "color",
        },
        "information-lighter": {
          value: "#021a2c",
          type: "color",
        },
        information: {
          value: "#0b78cb",
          type: "color",
        },
        inverse: {
          value: "#131416",
          type: "color",
        },
        "gray-dark": {
          value: "#8a949e",
          type: "color",
        },
        "inverse-static": {
          value: "#ffffff",
          type: "color",
        },
      },
      action: {
        white: {
          value: "#000000",
          type: "color",
          description: "disabled",
        },
        primary: {
          value: "#00000000",
          type: "color",
        },
        "primary-hover": {
          value: "#020f27",
          type: "color",
        },
        "primary-pressed": {
          value: "#03163a",
          type: "color",
        },
        secondary: {
          value: "#00000000",
          type: "color",
        },
        "secondary-hover": {
          value: "#091f25",
          type: "color",
        },
        "secondary-pressed": {
          value: "#0e3139",
          type: "color",
        },
        "secondary-selected": {
          value: "#091f25",
          type: "color",
        },
        "secondary-on": {
          value: "#00000000",
          type: "color",
        },
        "secondary-on-hover": {
          value: "#000000",
          type: "color",
        },
        "secondary-on-pressed": {
          value: "#0e3139",
          type: "color",
        },
        "secondary-on-selected": {
          value: "#131416",
          type: "color",
        },
        "secondary-active": {
          value: "#1f687a",
          type: "color",
        },
        "primary-active": {
          value: "#256ef4",
          type: "color",
        },
        disabled: {
          value: "#33363d",
          type: "color",
        },
        "primary-selected": {
          value: "#020f27",
          type: "color",
        },
      },
      input: {
        border: {
          value: "#8a949e",
          type: "color",
        },
        "border-disabled": {
          value: "#464c53",
          type: "color",
        },
        "border-active": {
          value: "#256ef4",
          type: "color",
          description: "active/selected",
        },
        "border-error": {
          value: "#de3412",
          type: "color",
        },
        surface: {
          value: "#1e2124",
          type: "color",
        },
        "surface-disabled": {
          value: "#131416",
          type: "color",
        },
      },
      graphic: {
        "blue-subtler": {
          value: "#e5ecf9",
          type: "color",
          description: "disabled",
        },
        "blue-subtle": {
          value: "#98acc5",
          type: "color",
          description: "disabled",
        },
        blue: {
          value: "#61758f",
          type: "color",
          description: "disabled",
        },
        "blue-dark": {
          value: "#39506c",
          type: "color",
          description: "disabled",
        },
        "blue-darker": {
          value: "#223a58",
          type: "color",
          description: "disabled",
        },
        "red-subtler": {
          value: "#fbeff0",
          type: "color",
          description: "disabled",
        },
        "red-subtle": {
          value: "#f5d6d9",
          type: "color",
          description: "disabled",
        },
        red: {
          value: "#ebadb2",
          type: "color",
          description: "disabled",
        },
        "red-dark": {
          value: "#d65c66",
          type: "color",
          description: "disabled",
        },
        "red-darker": {
          value: "#7a1f26",
          type: "color",
          description: "disabled",
        },
        brand: {
          value: "#256ef4",
          type: "color",
          description: "disabled",
        },
      },
      alpha: {
        base100: {
          value: "#000000",
          type: "color",
        },
        base50: {
          value: "#00000080",
          type: "color",
        },
        base25: {
          value: "#00000040",
          type: "color",
        },
        base0: {
          value: "#00000000",
          type: "color",
        },
        inverse100: {
          value: "#ffffff",
          type: "color",
        },
        inverse50: {
          value: "#ffffff80",
          type: "color",
        },
        inverse25: {
          value: "#ffffff40",
          type: "color",
        },
        inverse0: {
          value: "#ffffff00",
          type: "color",
        },
        base75: {
          value: "#000000bf",
          type: "color",
        },
        inverse75: {
          value: "#ffffffbf",
          type: "color",
        },
        inverse10: {
          value: "#00000040",
          type: "color",
        },
        base10: {
          value: "#0000001a",
          type: "color",
        },
        shadow1: {
          value: "#0000001f",
          type: "color",
        },
        shadow2: {
          value: "#00000033",
          type: "color",
        },
        shadow3: {
          value: "#00000066",
          type: "color",
        },
      },
    },
    "border-width": {
      "variable-regular": {
        value: "0.2rem",
        type: "dimension",
      },
      "variable-medium": {
        value: "0.3rem",
        type: "dimension",
      },
      "static-regular": {
        value: "0.1rem",
        type: "dimension",
      },
      "static-medium": {
        value: "0.2rem",
        type: "dimension",
      },
    },
  },
  "responsive-pc": {
    "font-size": {
      display: {
        large: {
          value: "6rem",
          type: "dimension",
        },
        medium: {
          value: "4.4rem",
          type: "dimension",
        },
        small: {
          value: "3.6rem",
          type: "dimension",
        },
      },
      body: {
        large: {
          value: "1.9rem",
          type: "dimension",
        },
        medium: {
          value: "1.7rem",
          type: "dimension",
        },
        small: {
          value: "1.5rem",
          type: "dimension",
        },
        xsmall: {
          value: "1.3rem",
          type: "dimension",
        },
      },
      label: {
        large: {
          value: "1.9rem",
          type: "dimension",
        },
        medium: {
          value: "1.7rem",
          type: "dimension",
        },
        small: {
          value: "1.5rem",
          type: "dimension",
        },
        xsmall: {
          value: "1.3rem",
          type: "dimension",
        },
      },
      heading: {
        large: {
          value: "3.2rem",
          type: "dimension",
        },
        medium: {
          value: "2.4rem",
          type: "dimension",
        },
        small: {
          value: "1.9rem",
          type: "dimension",
        },
        xsmall: {
          value: "1.7rem",
          type: "dimension",
        },
        xxsmall: {
          value: "1.5rem",
          type: "dimension",
        },
        xlarge: {
          value: "4rem",
          type: "dimension",
        },
      },
      navigation: {
        "title-medium": {
          value: "2.4rem",
          type: "dimension",
        },
        "title-small": {
          value: "1.9rem",
          type: "dimension",
        },
        "depth-medium-bold": {
          value: "1.7rem",
          type: "dimension",
        },
        "depth-medium": {
          value: "1.7rem",
          type: "dimension",
        },
        "depth-small-bold": {
          value: "1.5rem",
          type: "dimension",
        },
        "depth-small": {
          value: "1.5rem",
          type: "dimension",
        },
      },
    },
    "gap-layout": {
      "header-breadcrumb": {
        value: "2.4rem",
        type: "dimension",
      },
      "left-contents": {
        value: "6.4rem",
        type: "dimension",
      },
      "contents-right": {
        value: "4rem",
        type: "dimension",
      },
      "h1-h2": {
        value: "4.8rem",
        type: "dimension",
      },
      "h2-h2": {
        value: "8rem",
        type: "dimension",
      },
      "h2-h3": {
        value: "4rem",
        type: "dimension",
      },
      "h3-h3": {
        value: "6.4rem",
        type: "dimension",
      },
      "h3-h4": {
        value: "2.4rem",
        type: "dimension",
      },
      "h4-h4": {
        value: "4rem",
        type: "dimension",
      },
      "h4-h5": {
        value: "1.6rem",
        type: "dimension",
      },
      "h5-h5": {
        value: "3.2rem",
        type: "dimension",
      },
      "title-body-small": {
        value: "1.6rem",
        type: "dimension",
      },
      "title-body-medium": {
        value: "2rem",
        type: "dimension",
      },
      "title-body-large": {
        value: "2.4rem",
        type: "dimension",
      },
      "breadcrumb-h1": {
        value: "4rem",
        type: "dimension",
      },
      "contents-footer": {
        value: "6.4rem",
        type: "dimension",
      },
      "text-text-large": {
        value: "2rem",
        type: "dimension",
      },
      "text-text-medium": {
        value: "1.6rem",
        type: "dimension",
      },
      "text-text-small": {
        value: "1.2rem",
        type: "dimension",
      },
      "image-text-small": {
        value: "2rem",
        type: "dimension",
      },
      "image-text-medium": {
        value: "2.4rem",
        type: "dimension",
      },
      "image-text-large": {
        value: "3.2rem",
        type: "dimension",
      },
    },
    "padding-card": {
      large: {
        value: "4rem",
        type: "dimension",
      },
      medium: {
        value: "3.2rem",
        type: "dimension",
      },
      small: {
        value: "2.4rem",
        type: "dimension",
      },
      xsmall: {
        value: "1.6rem",
        type: "dimension",
      },
    },
  },
  "responsive-mobile": {
    "font-size": {
      display: {
        large: {
          value: "4.4rem",
          type: "dimension",
        },
        medium: {
          value: "3.2rem",
          type: "dimension",
        },
        small: {
          value: "2.8rem",
          type: "dimension",
        },
      },
      body: {
        large: {
          value: "1.9rem",
          type: "dimension",
        },
        medium: {
          value: "1.7rem",
          type: "dimension",
        },
        small: {
          value: "1.5rem",
          type: "dimension",
        },
        xsmall: {
          value: "1.3rem",
          type: "dimension",
        },
      },
      label: {
        large: {
          value: "1.9rem",
          type: "dimension",
        },
        medium: {
          value: "1.7rem",
          type: "dimension",
        },
        small: {
          value: "1.5rem",
          type: "dimension",
        },
        xsmall: {
          value: "1.3rem",
          type: "dimension",
        },
      },
      heading: {
        large: {
          value: "2.4rem",
          type: "dimension",
        },
        medium: {
          value: "2.2rem",
          type: "dimension",
        },
        small: {
          value: "1.9rem",
          type: "dimension",
        },
        xsmall: {
          value: "1.7rem",
          type: "dimension",
        },
        xxsmall: {
          value: "1.5rem",
          type: "dimension",
        },
        xlarge: {
          value: "2.8rem",
          type: "dimension",
        },
      },
      navigation: {
        "title-medium": {
          value: "2.2rem",
          type: "dimension",
        },
        "title-small": {
          value: "1.9rem",
          type: "dimension",
        },
        "depth-medium-bold": {
          value: "1.7rem",
          type: "dimension",
        },
        "depth-medium": {
          value: "1.7rem",
          type: "dimension",
        },
        "depth-small-bold": {
          value: "1.5rem",
          type: "dimension",
        },
        "depth-small": {
          value: "1.5rem",
          type: "dimension",
        },
      },
    },
    "gap-layout": {
      "header-breadcrumb": {
        value: "1.6rem",
        type: "dimension",
      },
      "left-contents": {
        value: "0rem",
        type: "dimension",
      },
      "contents-right": {
        value: "0rem",
        type: "dimension",
      },
      "h1-h2": {
        value: "3.2rem",
        type: "dimension",
      },
      "h2-h2": {
        value: "4rem",
        type: "dimension",
      },
      "h2-h3": {
        value: "2.4rem",
        type: "dimension",
      },
      "h3-h3": {
        value: "3.2rem",
        type: "dimension",
      },
      "h3-h4": {
        value: "1.6rem",
        type: "dimension",
      },
      "h4-h4": {
        value: "2.4rem",
        type: "dimension",
      },
      "h4-h5": {
        value: "1.2rem",
        type: "dimension",
      },
      "h5-h5": {
        value: "1.6rem",
        type: "dimension",
      },
      "title-body-small": {
        value: "0.8rem",
        type: "dimension",
      },
      "title-body-medium": {
        value: "1.2rem",
        type: "dimension",
      },
      "title-body-large": {
        value: "2rem",
        type: "dimension",
      },
      "breadcrumb-h1": {
        value: "3.2rem",
        type: "dimension",
      },
      "contents-footer": {
        value: "4rem",
        type: "dimension",
      },
      "text-text-large": {
        value: "1.6rem",
        type: "dimension",
      },
      "text-text-medium": {
        value: "1.2rem",
        type: "dimension",
      },
      "text-text-small": {
        value: "1rem",
        type: "dimension",
      },
      "image-text-small": {
        value: "1.6rem",
        type: "dimension",
      },
      "image-text-medium": {
        value: "2rem",
        type: "dimension",
      },
      "image-text-large": {
        value: "2.4rem",
        type: "dimension",
      },
    },
    "padding-card": {
      large: {
        value: "2.4rem",
        type: "dimension",
      },
      medium: {
        value: "2.4rem",
        type: "dimension",
      },
      small: {
        value: "2rem",
        type: "dimension",
      },
      xsmall: {
        value: "1.2rem",
        type: "dimension",
      },
    },
  },
  semantic: {
    gap: {
      "1": {
        value: "0.2rem",
        type: "dimension",
      },
      "2": {
        value: "0.4rem",
        type: "dimension",
      },
      "3": {
        value: "0.8rem",
        type: "dimension",
      },
      "4": {
        value: "1.2rem",
        type: "dimension",
      },
      "5": {
        value: "1.6rem",
        type: "dimension",
      },
      "6": {
        value: "2rem",
        type: "dimension",
      },
      "7": {
        value: "2.4rem",
        type: "dimension",
      },
      "8": {
        value: "3.2rem",
        type: "dimension",
      },
      "9": {
        value: "4rem",
        type: "dimension",
      },
      "10": {
        value: "4.8rem",
        type: "dimension",
      },
      "11": {
        value: "6.4rem",
        type: "dimension",
      },
      "12": {
        value: "8rem",
        type: "dimension",
      },
    },
    padding: {
      "1": {
        value: "0.2rem",
        type: "dimension",
      },
      "2": {
        value: "0.4rem",
        type: "dimension",
      },
      "3": {
        value: "0.8rem",
        type: "dimension",
      },
      "4": {
        value: "1rem",
        type: "dimension",
      },
      "5": {
        value: "1.2rem",
        type: "dimension",
      },
      "6": {
        value: "1.6rem",
        type: "dimension",
      },
      "7": {
        value: "2rem",
        type: "dimension",
      },
      "8": {
        value: "2.4rem",
        type: "dimension",
      },
      "9": {
        value: "3.2rem",
        type: "dimension",
      },
      "10": {
        value: "4rem",
        type: "dimension",
      },
    },
    "size-height": {
      "1": {
        value: "0.8rem",
        type: "dimension",
      },
      "2": {
        value: "1.6rem",
        type: "dimension",
      },
      "3": {
        value: "2rem",
        type: "dimension",
      },
      "4": {
        value: "2.4rem",
        type: "dimension",
      },
      "5": {
        value: "3.2rem",
        type: "dimension",
      },
      "6": {
        value: "4rem",
        type: "dimension",
      },
      "7": {
        value: "4.8rem",
        type: "dimension",
      },
      "8": {
        value: "5.6rem",
        type: "dimension",
      },
      "9": {
        value: "6.4rem",
        type: "dimension",
      },
      "10": {
        value: "7.2rem",
        type: "dimension",
      },
      "11": {
        value: "8rem",
        type: "dimension",
      },
    },
    radius: {
      xsmall1: {
        value: "0.2rem",
        type: "dimension",
      },
      xsmall2: {
        value: "0.2rem",
        type: "dimension",
      },
      xsmall3: {
        value: "0.2rem",
        type: "dimension",
      },
      small1: {
        value: "0.4rem",
        type: "dimension",
      },
      small2: {
        value: "0.4rem",
        type: "dimension",
      },
      small3: {
        value: "0.4rem",
        type: "dimension",
      },
      medium1: {
        value: "0.6rem",
        type: "dimension",
      },
      medium2: {
        value: "0.6rem",
        type: "dimension",
      },
      medium3: {
        value: "0.8rem",
        type: "dimension",
      },
      medium4: {
        value: "0.8rem",
        type: "dimension",
      },
      large1: {
        value: "1rem",
        type: "dimension",
      },
      large2: {
        value: "1rem",
        type: "dimension",
      },
      xlarge1: {
        value: "1.2rem",
        type: "dimension",
      },
      xlarge2: {
        value: "1.2rem",
        type: "dimension",
      },
      max: {
        value: "100rem",
        type: "dimension",
      },
    },
  },
} as const;

export default TOKENS;
