import type { Metadata } from "next";
import type { ReactNode } from "react";

import "@gracefullight/krds/reset.css";
import "@/app/globals.css";
import Providers from "@/components/providers";
import pretendardGov from "@/lib/fonts";
import { Container } from "@mui/material";

export const metadata: Metadata = {
  title: {
    default: "KRDS Sample",
    template: "% | KRDS Sample",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ko" className={pretendardGov.className}>
      <body>
        <Providers>
          <Container maxWidth="xlarge" component="main">
            {children}
          </Container>
        </Providers>
      </body>
    </html>
  );
}
