import type { Metadata } from "next";
import type { ReactNode } from "react";

import "@gracefullight/krds/reset.css";
import "@/app/globals.css";
import Providers from "@/components/providers";
import pretendardGov from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ko" className={pretendardGov.className}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
